/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Menuusages;

import Containers.ContenedoraEmpleado;
import Mail.Correos;
import MenuIU.Menu;
import Model.Cargo;
import Model.Empleado;
import Webcam.WebcamClass;
import java.awt.Color;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.File;
import java.io.IOException;
import java.util.logging.Logger;
import java.util.logging.Level;

import java.time.LocalDate;
import java.util.HashMap;
import java.util.Map;


import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import rsdragdropfiles.RSDragDropFiles;

/**
 *
 * @author nicol
 */
public class ModificarEmpleado extends javax.swing.JFrame {

    int xMouse, yMouse;
    LocalDate fechaVen;
    LocalDate fechaRe;
    /**
     * Creates new form ModificarEmpleado
     */
    public ModificarEmpleado(LocalDate fechaV,LocalDate fechaR, int legajo,String nombre, String apellido, int documento,String fechaNac,String email, Cargo cargoSeleccionada) throws UnsupportedLookAndFeelException {
        initComponents();
        fechaVen = fechaV;
        fechaRe = fechaR;
        legajoTxt.setText(String.valueOf(legajo));
        legajoTxt.setEditable(false);
        legajoTxt.setForeground(Color.black);

        fechaNacTxt.setText(fechaNac);
        fechaNacTxt.setForeground(Color.black);

        nombreTxt.setText(nombre);
        nombreTxt.setForeground(Color.black);

        apellidoTxt.setText(apellido);
        apellidoTxt.setForeground(Color.black);

        dniTxt.setText(String.valueOf(documento));
        dniTxt.setForeground(Color.black);

        emailTxt.setText(email);
        emailTxt.setForeground(Color.black);


        cargoBox.setSelectedItem(cargoSeleccionada);
        cargoBox.setForeground(Color.black);


        setDate();
        for (Cargo cargo : Cargo.values()) {
            cargoBox.addItem(String.valueOf(cargo));
        }

        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(InfoEmpleado.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(InfoEmpleado.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(InfoEmpleado.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(InfoEmpleado.class.getName()).log(Level.SEVERE, null, ex);
        }
      
    }
    
    private void setDate(){
        LocalDate now = LocalDate.now();
        int year = now.getYear();
        int dia = now.getDayOfMonth();
        int month = now.getMonthValue();
        String[] meses = {"Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre"};
        dateText.setText(dia+" de "+meses[month -1]+" de "+year);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        exitMenu = new javax.swing.JPanel();
        exitBtn = new javax.swing.JPanel();
        exitTxt = new javax.swing.JLabel();
        header = new javax.swing.JPanel();
        administracionTxt = new javax.swing.JLabel();
        dateText = new javax.swing.JLabel();
        panelVentanas = new javax.swing.JTabbedPane();
        ventana1 = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        nombre = new javax.swing.JLabel();
        nombreTxt = new javax.swing.JTextField();
        nombreSep = new javax.swing.JSeparator();
        apellido = new javax.swing.JLabel();
        apellidoTxt = new javax.swing.JTextField();
        apellidoSep = new javax.swing.JSeparator();
        dni = new javax.swing.JLabel();
        dniTxt = new javax.swing.JTextField();
        dniSep = new javax.swing.JSeparator();
        legajo = new javax.swing.JLabel();
        legajoTxt = new javax.swing.JTextField();
        legajoSep = new javax.swing.JSeparator();
        email = new javax.swing.JLabel();
        emailTxt = new javax.swing.JTextField();
        emailSep = new javax.swing.JSeparator();
        fechaNac = new javax.swing.JLabel();
        fechaNacTxt = new javax.swing.JTextField();
        fechaNacSep = new javax.swing.JSeparator();
        cargo = new javax.swing.JLabel();
        cargoBox = new javax.swing.JComboBox<>();
        modifBtn = new javax.swing.JPanel();
        modifTxt = new javax.swing.JLabel();
        cargarImgBtn = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Volver al Menu");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        background.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 670, -1, -1));

        exitMenu.setBackground(new java.awt.Color(255, 255, 255));
        exitMenu.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                exitMenuMouseDragged(evt);
            }
        });
        exitMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                exitMenuMousePressed(evt);
            }
        });
        exitMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exitBtn.setBackground(new java.awt.Color(255, 255, 255));

        exitTxt.setBackground(new java.awt.Color(0, 0, 0));
        exitTxt.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        exitTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitTxt.setText("X");
        exitTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitTxtMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                exitTxtMousePressed(evt);
            }
        });

        javax.swing.GroupLayout exitBtnLayout = new javax.swing.GroupLayout(exitBtn);
        exitBtn.setLayout(exitBtnLayout);
        exitBtnLayout.setHorizontalGroup(
            exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
            .addGroup(exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(exitBtnLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(exitTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        exitBtnLayout.setVerticalGroup(
            exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
            .addGroup(exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(exitBtnLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(exitTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        exitMenu.add(exitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 0, -1, -1));

        background.add(exitMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        header.setBackground(new java.awt.Color(50, 115, 153));

        administracionTxt.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        administracionTxt.setForeground(new java.awt.Color(255, 255, 255));
        administracionTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        administracionTxt.setText("EMPLEADOS");

        dateText.setFont(new java.awt.Font("Roboto", 1, 30)); // NOI18N
        dateText.setForeground(new java.awt.Color(255, 255, 255));
        dateText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dateText.setText("{dayname} {day} de {month} de {year} ");

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dateText)
                    .addComponent(administracionTxt))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(administracionTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(dateText)
                .addGap(34, 34, 34))
        );

        background.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 600, 160));

        ventana1.setBackground(new java.awt.Color(255, 255, 255));
        ventana1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("MODIFICAR EMPLEADO");
        ventana1.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 280, 50));

        nombre.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        nombre.setText("NOMBRE");
        ventana1.add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, -1, -1));

        nombreTxt.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        nombreTxt.setForeground(new java.awt.Color(153, 153, 153));
        nombreTxt.setText("Ingrese el nombre");
        nombreTxt.setBorder(null);
        nombreTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                nombreTxtMousePressed(evt);
            }
        });
        nombreTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreTxtActionPerformed(evt);
            }
        });
        nombreTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nombreTxtKeyTyped(evt);
            }
        });
        ventana1.add(nombreTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 180, 30));
        ventana1.add(nombreSep, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, 180, 10));

        apellido.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        apellido.setText("APELLIDO");
        ventana1.add(apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, -1, -1));

        apellidoTxt.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        apellidoTxt.setForeground(new java.awt.Color(153, 153, 153));
        apellidoTxt.setText("Ingrese el apellido");
        apellidoTxt.setBorder(null);
        apellidoTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                apellidoTxtMousePressed(evt);
            }
        });
        apellidoTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apellidoTxtActionPerformed(evt);
            }
        });
        apellidoTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                apellidoTxtKeyTyped(evt);
            }
        });
        ventana1.add(apellidoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, 180, 30));
        ventana1.add(apellidoSep, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 450, 180, 10));

        dni.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        dni.setText("DOCUMENTO");
        ventana1.add(dni, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 480, -1, -1));

        dniTxt.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        dniTxt.setForeground(new java.awt.Color(153, 153, 153));
        dniTxt.setText("Ingrese el documento");
        dniTxt.setBorder(null);
        dniTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                dniTxtMousePressed(evt);
            }
        });
        dniTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dniTxtActionPerformed(evt);
            }
        });
        dniTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                dniTxtKeyTyped(evt);
            }
        });
        ventana1.add(dniTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 500, 180, 30));
        ventana1.add(dniSep, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 530, 180, 10));

        legajo.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        legajo.setText("LEGAJO");
        ventana1.add(legajo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 560, -1, -1));

        legajoTxt.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        legajoTxt.setForeground(new java.awt.Color(153, 153, 153));
        legajoTxt.setText("Ingrese el legajo");
        legajoTxt.setBorder(null);
        legajoTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        legajoTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                legajoTxtMousePressed(evt);
            }
        });
        legajoTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                legajoTxtActionPerformed(evt);
            }
        });
        legajoTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                legajoTxtKeyTyped(evt);
            }
        });
        ventana1.add(legajoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 580, 180, 30));
        ventana1.add(legajoSep, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 610, 180, 10));

        email.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        email.setText("CORREO ELECTRONICO");
        ventana1.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 320, -1, -1));

        emailTxt.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        emailTxt.setForeground(new java.awt.Color(153, 153, 153));
        emailTxt.setText("Ingrese el email");
        emailTxt.setBorder(null);
        emailTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                emailTxtMousePressed(evt);
            }
        });
        emailTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTxtActionPerformed(evt);
            }
        });
        ventana1.add(emailTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 340, 180, 30));
        ventana1.add(emailSep, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 370, 180, 10));

        fechaNac.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        fechaNac.setText("FECHA DE NACIMIENTO");
        ventana1.add(fechaNac, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 400, -1, -1));

        fechaNacTxt.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        fechaNacTxt.setForeground(new java.awt.Color(153, 153, 153));
        fechaNacTxt.setText("dd/mm/aaaa");
        fechaNacTxt.setBorder(null);
        fechaNacTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                fechaNacTxtMousePressed(evt);
            }
        });
        fechaNacTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechaNacTxtActionPerformed(evt);
            }
        });
        ventana1.add(fechaNacTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 420, 180, 30));
        ventana1.add(fechaNacSep, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 450, 180, 10));

        cargo.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        cargo.setText("CARGO");
        ventana1.add(cargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 470, -1, -1));

        cargoBox.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cargoBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cargoBoxMousePressed(evt);
            }
        });
        cargoBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargoBoxActionPerformed(evt);
            }
        });
        ventana1.add(cargoBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 500, 180, 30));

        modifBtn.setBackground(new java.awt.Color(50, 115, 153));

        modifTxt.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        modifTxt.setForeground(new java.awt.Color(255, 255, 255));
        modifTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        modifTxt.setText("MODIFICAR");
        modifTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        modifTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                modifTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                modifTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                modifTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout modifBtnLayout = new javax.swing.GroupLayout(modifBtn);
        modifBtn.setLayout(modifBtnLayout);
        modifBtnLayout.setHorizontalGroup(
            modifBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(modifTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
        );
        modifBtnLayout.setVerticalGroup(
            modifBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(modifTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        ventana1.add(modifBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 660, 240, 50));

        cargarImgBtn.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout cargarImgBtnLayout = new javax.swing.GroupLayout(cargarImgBtn);
        cargarImgBtn.setLayout(cargarImgBtnLayout);
        cargarImgBtnLayout.setHorizontalGroup(
            cargarImgBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        cargarImgBtnLayout.setVerticalGroup(
            cargarImgBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        ventana1.add(cargarImgBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 490, -1, 20));

        panelVentanas.addTab("tab1", ventana1);

        background.add(panelVentanas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -40, 1280, 760));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitTxtMouseClicked

    private void exitTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMouseEntered
        exitBtn.setBackground(Color.red);
        exitTxt.setForeground(Color.white);
    }//GEN-LAST:event_exitTxtMouseEntered

    private void exitTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMouseExited
        exitBtn.setBackground(Color.white);
        exitTxt.setForeground(Color.black);
    }//GEN-LAST:event_exitTxtMouseExited

    private void exitTxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_exitTxtMousePressed

    private void exitMenuMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMenuMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_exitMenuMouseDragged

    private void exitMenuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMenuMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_exitMenuMousePressed

    private void nombreTxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nombreTxtMousePressed
        if (nombreTxt.getText().equals("Ingrese el nombre")) {
            nombreTxt.setText("");
            nombreTxt.setForeground(Color.black);
        }
        if (apellidoTxt.getText().equals("")) {
            apellidoTxt.setText("Ingrese el apellido");
            apellidoTxt.setForeground(Color.gray);
        }
        if (dniTxt.getText().equals("")) {
            dniTxt.setText("Ingrese el documento");
            dniTxt.setForeground(Color.gray);
        }
        if (legajoTxt.getText().equals("")) {
            legajoTxt.setText("Ingrese el legajo");
            legajoTxt.setForeground(Color.gray);
        }
        if (emailTxt.getText().equals("")) {
            emailTxt.setText("Ingrese el email");
            emailTxt.setForeground(Color.gray);
        }
        if (fechaNacTxt.getText().equals("")) {
            fechaNacTxt.setText("dd/mm/aaaa");
            fechaNacTxt.setForeground(Color.gray);
        }
        
      
      
    }//GEN-LAST:event_nombreTxtMousePressed

    private void nombreTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreTxtActionPerformed

    private void nombreTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombreTxtKeyTyped
        char c = evt.getKeyChar();

        if ((c < 'a' || c > 'z') && (c < 'A' || c > 'Z') && c != ' ')
        evt.consume();
    }//GEN-LAST:event_nombreTxtKeyTyped

    private void apellidoTxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_apellidoTxtMousePressed
        if (apellidoTxt.getText().equals("Ingrese el apellido")) {
            apellidoTxt.setText("");
            apellidoTxt.setForeground(Color.black);
        }
        if (nombreTxt.getText().equals("")) {
            nombreTxt.setText("Ingrese el nombre");
            nombreTxt.setForeground(Color.gray);
        }
        if (dniTxt.getText().equals("")) {
            dniTxt.setText("Ingrese el documento");
            dniTxt.setForeground(Color.gray);
        }
        if (legajoTxt.getText().equals("")) {
            legajoTxt.setText("Ingrese el legajo");
            legajoTxt.setForeground(Color.gray);
        }
        if (emailTxt.getText().equals("")) {
            emailTxt.setText("Ingrese el email");
            emailTxt.setForeground(Color.gray);
        }
      
        if (fechaNacTxt.getText().equals("dd/mm/aaaa")) {
            fechaNacTxt.setText("dd/mm/aaaa");
            fechaNacTxt.setForeground(Color.gray);
        }
   
       
    }//GEN-LAST:event_apellidoTxtMousePressed

    private void apellidoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apellidoTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apellidoTxtActionPerformed

    private void apellidoTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_apellidoTxtKeyTyped
        char c = evt.getKeyChar();

        if ((c < 'a' || c > 'z') && (c < 'A' || c > 'Z') && c != ' ')
        evt.consume();
    }//GEN-LAST:event_apellidoTxtKeyTyped

    private void dniTxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dniTxtMousePressed
        if (apellidoTxt.getText().equals("")) {
            apellidoTxt.setText("Ingrese el apellido");
            apellidoTxt.setForeground(Color.gray);
        }
        if (nombreTxt.getText().equals("")) {
            nombreTxt.setText("Ingrese el nombre");
            nombreTxt.setForeground(Color.gray);
        }
        if (dniTxt.getText().equals("Ingrese el documento")) {
            dniTxt.setText("");
            dniTxt.setForeground(Color.black);
        }
        if (legajoTxt.getText().equals("")) {
            legajoTxt.setText("Ingrese el legajo");
            legajoTxt.setForeground(Color.gray);
        }
        if (emailTxt.getText().equals("")) {
            emailTxt.setText("Ingrese el email");
            emailTxt.setForeground(Color.gray);
        }
        
        if (fechaNacTxt.getText().equals("")) {
            fechaNacTxt.setText("dd/mm/aaaa");
            fechaNacTxt.setForeground(Color.gray);
        }
       
     
        
    }//GEN-LAST:event_dniTxtMousePressed

    private void dniTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dniTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dniTxtActionPerformed

    private void dniTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dniTxtKeyTyped
        char c = evt.getKeyChar();

        if (c < '0' || c > '9')
        evt.consume();
    }//GEN-LAST:event_dniTxtKeyTyped

    private void legajoTxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_legajoTxtMousePressed
        if (apellidoTxt.getText().equals("")) {
            apellidoTxt.setText("Ingrese el apellido");
            apellidoTxt.setForeground(Color.gray);
        }
        if (nombreTxt.getText().equals("")) {
            nombreTxt.setText("Ingrese el nombre");
            nombreTxt.setForeground(Color.gray);
        }
        if (dniTxt.getText().equals("")) {
            dniTxt.setText("Ingrese el documento");
            dniTxt.setForeground(Color.gray);
        }
        if (legajoTxt.getText().equals("Ingrese el legajo")) {
            legajoTxt.setText("");
            legajoTxt.setForeground(Color.black);
        }
        if (emailTxt.getText().equals("")) {
            emailTxt.setText("Ingrese el email");
            emailTxt.setForeground(Color.gray);
        }
       
        if (fechaNacTxt.getText().equals("")) {
            fechaNacTxt.setText("dd/mm/aaaa");
            fechaNacTxt.setForeground(Color.gray);
        }
        
   
        
    }//GEN-LAST:event_legajoTxtMousePressed

    private void legajoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_legajoTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_legajoTxtActionPerformed

    private void legajoTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_legajoTxtKeyTyped
        char c = evt.getKeyChar();

        if (c < '0' || c > '9')
        evt.consume();
    }//GEN-LAST:event_legajoTxtKeyTyped

    private void emailTxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emailTxtMousePressed
        if (apellidoTxt.getText().equals("")) {
            apellidoTxt.setText("Ingrese el apellido");
            apellidoTxt.setForeground(Color.gray);
        }
        if (nombreTxt.getText().equals("")) {
            nombreTxt.setText("Ingrese el nombre");
            nombreTxt.setForeground(Color.gray);
        }
        if (dniTxt.getText().equals("")) {
            dniTxt.setText("Ingrese el documento");
            dniTxt.setForeground(Color.gray);
        }
        if (legajoTxt.getText().equals("")) {
            legajoTxt.setText("Ingrese el legajo");
            legajoTxt.setForeground(Color.gray);
        }
        if (emailTxt.getText().equals("Ingrese el email")) {
            emailTxt.setText("");
            emailTxt.setForeground(Color.black);
        }
       
        if (fechaNacTxt.getText().equals("")) {
            fechaNacTxt.setText("dd/mm/aaaa");
            fechaNacTxt.setForeground(Color.gray);
        }
        
    
     
    }//GEN-LAST:event_emailTxtMousePressed

    private void emailTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTxtActionPerformed

    private void fechaNacTxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fechaNacTxtMousePressed

        if (apellidoTxt.getText().equals("")) {
            apellidoTxt.setText("Ingrese el apellido");
            apellidoTxt.setForeground(Color.gray);
        }
        if (nombreTxt.getText().equals("")) {
            nombreTxt.setText("Ingrese el nombre");
            nombreTxt.setForeground(Color.gray);
        }
        if (dniTxt.getText().equals("")) {
            dniTxt.setText("Ingrese el documento");
            dniTxt.setForeground(Color.gray);
        }
        if (legajoTxt.getText().equals("")) {
            legajoTxt.setText("Ingrese el legajo");
            legajoTxt.setForeground(Color.gray);
        }
        if (emailTxt.getText().equals("")) {
            emailTxt.setText("Ingrese el email");
            emailTxt.setForeground(Color.gray);
        }
        
        if (fechaNacTxt.getText().equals("dd/mm/aaaa")) {
            fechaNacTxt.setText("");
            fechaNacTxt.setForeground(Color.black);
        }

        
    
       
    }//GEN-LAST:event_fechaNacTxtMousePressed

    private void fechaNacTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechaNacTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fechaNacTxtActionPerformed

    private void cargoBoxMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cargoBoxMousePressed
        if (apellidoTxt.getText().equals("")) {
            apellidoTxt.setText("Ingrese el apellido");
            apellidoTxt.setForeground(Color.gray);
        }
        if (nombreTxt.getText().equals("")) {
            nombreTxt.setText("Ingrese el nombre");
            nombreTxt.setForeground(Color.gray);
        }
        if (dniTxt.getText().equals("")) {
            dniTxt.setText("Ingrese el documento");
            dniTxt.setForeground(Color.gray);
        }
        if (legajoTxt.getText().equals("")) {
            legajoTxt.setText("Ingrese el legajo");
            legajoTxt.setForeground(Color.gray);
        }
        if (emailTxt.getText().equals("")) {
            emailTxt.setText("Ingrese el email");
            emailTxt.setForeground(Color.gray);
        }
     
        if (fechaNacTxt.getText().equals("")) {
            fechaNacTxt.setText("dd/mm/aaaa");
            fechaNacTxt.setForeground(Color.gray);
        }
      
     
      
    }//GEN-LAST:event_cargoBoxMousePressed

    private LocalDate parseDate(String dateStr) {
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        try {
            return LocalDate.parse(dateStr, formatter);
        } catch (DateTimeParseException e) {
            return null;
        }
    }
    
    private boolean isAnyFieldEmpty() {
        boolean anyFieldEmpty = nombreTxt.getText().isEmpty() || nombreTxt.getText().equals("Ingrese el nombre")
                || apellidoTxt.getText().isEmpty() || apellidoTxt.getText().equals("Ingrese el apellido")
                || dniTxt.getText().isEmpty() || dniTxt.getText().equals("Ingrese el documento")
                || legajoTxt.getText().isEmpty() || legajoTxt.getText().equals("Ingrese el legajo")
                || emailTxt.getText().isEmpty() || emailTxt.getText().equals("Ingrese el email")
                || fechaNacTxt.getText().isEmpty() || fechaNacTxt.getText().equals("dd/mm/aaaa");

        Object selectedCargo = cargoBox.getSelectedItem();
        if (selectedCargo == null || selectedCargo.toString().isEmpty()) {
            anyFieldEmpty = true;
        }
        return anyFieldEmpty;
    }
    
    
    public static boolean isValidEmail(String email) {
        // Expresión regular para validar el correo electrónico
        String emailRegex = "^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,6}$";
        Pattern pattern = Pattern.compile(emailRegex);
        Matcher matcher = pattern.matcher(email);
        return matcher.matches();
    }
    
    
    private void modifTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modifTxtMouseClicked
        ContenedoraEmpleado contenedoraEmpleado = new ContenedoraEmpleado();
        Correos mail = new Correos();
        try {
            contenedoraEmpleado.cargarEmpleadosDeJson("Empleados.json");
        } catch (IOException e) {
            e.printStackTrace();
        }
        String dateOfBirthStr = fechaNacTxt.getText();
        String email = emailTxt.getText();
        LocalDate dateOfBirth = parseDate(dateOfBirthStr);
        String selectedCargoString = cargoBox.getSelectedItem().toString();
        String dniStr = dniTxt.getText();
        // Crear el mapa de categorías
        Map<String, Cargo> cargoMap = new HashMap<>();
        for (Cargo cargo : Cargo.values()) {
            cargoMap.put(cargo.toString(), cargo);
        }

        // Obtener la categoría seleccionada del mapa
        Cargo selectedCargo = cargoMap.get(selectedCargoString);
        if (isAnyFieldEmpty()) {
            JOptionPane.showMessageDialog(this, "Todos los campos deben estar llenos.", "Error de registro", JOptionPane.ERROR_MESSAGE);
        } else if (!isValidEmail(email)) {
            JOptionPane.showMessageDialog(this, "La direccion de Email no es valida, ingrese nuevamente.", "Error de registro", JOptionPane.ERROR_MESSAGE);
        } else if (dateOfBirth == null) {
            JOptionPane.showMessageDialog(this, "La fecha de nacimiento no es válida. Use el formato dd/MM/yyyy.", "Error de registro", JOptionPane.ERROR_MESSAGE);
        } else if (dniStr.length() != 8) {
            JOptionPane.showMessageDialog(this, "El DNI debe tener exactamente 8 caracteres.", "Error de registro", JOptionPane.ERROR_MESSAGE);
        }else {
            try {

                Empleado e = new Empleado(nombreTxt.getText(), apellidoTxt.getText(), Integer.parseInt(dniStr), Integer.parseInt(legajoTxt.getText()), emailTxt.getText(), fechaNacTxt.getText(), legajo.getText()+selectedCargo, selectedCargo, true);
                e.setFechaRegistroPago(fechaRe);
                e.setFechaVencimientoPago(fechaVen);
                contenedoraEmpleado.modificacion(e);

                contenedoraEmpleado.guardarEmpleadosEnJson("Empleados.json");

                //Barra de carga antes de mandar a registro exitoso (Opcional)
                ModifExitosa modifEx = new ModifExitosa();
                modifEx.setVisible(true);
                modifEx.pack();
                modifEx.setLocationRelativeTo(null);

                this.dispose();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage(), "Error de modificacion", JOptionPane.ERROR_MESSAGE);

            }

        }
    }//GEN-LAST:event_modifTxtMouseClicked

    private void modifTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modifTxtMouseEntered
        modifBtn.setBackground(new Color(80,139,166));
    }//GEN-LAST:event_modifTxtMouseEntered

    private void modifTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modifTxtMouseExited
        modifBtn.setBackground(new Color(59,132,173));
    }//GEN-LAST:event_modifTxtMouseExited

    private void cargoBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargoBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cargoBoxActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        Menu menu = new Menu();
        menu.setVisible(true);
        menu.pack();
        menu.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel administracionTxt;
    private javax.swing.JLabel apellido;
    private javax.swing.JSeparator apellidoSep;
    private javax.swing.JTextField apellidoTxt;
    private javax.swing.JPanel background;
    private javax.swing.JPanel cargarImgBtn;
    private javax.swing.JLabel cargo;
    private javax.swing.JComboBox<String> cargoBox;
    private javax.swing.JLabel dateText;
    private javax.swing.JLabel dni;
    private javax.swing.JSeparator dniSep;
    private javax.swing.JTextField dniTxt;
    private javax.swing.JLabel email;
    private javax.swing.JSeparator emailSep;
    private javax.swing.JTextField emailTxt;
    private javax.swing.JPanel exitBtn;
    private javax.swing.JPanel exitMenu;
    private javax.swing.JLabel exitTxt;
    private javax.swing.JLabel fechaNac;
    private javax.swing.JSeparator fechaNacSep;
    private javax.swing.JTextField fechaNacTxt;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel legajo;
    private javax.swing.JSeparator legajoSep;
    private javax.swing.JTextField legajoTxt;
    private javax.swing.JPanel modifBtn;
    private javax.swing.JLabel modifTxt;
    private javax.swing.JLabel nombre;
    private javax.swing.JSeparator nombreSep;
    private javax.swing.JTextField nombreTxt;
    private javax.swing.JTabbedPane panelVentanas;
    private javax.swing.JLabel titulo;
    private javax.swing.JPanel ventana1;
    // End of variables declaration//GEN-END:variables
}
