/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Menuusages;

import MenuIU.Menu;
import java.awt.Color;

/**
 *
 * @author santi
 */
public class PagoExitoso extends javax.swing.JFrame {

    /**
     * Creates new form PagoExitoso
     */
    public PagoExitoso() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        Tick = new javax.swing.JLabel();
        pagoExitoso = new javax.swing.JLabel();
        mensajeTxt = new javax.swing.JLabel();
        okBtn = new javax.swing.JPanel();
        okBtnTxt = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Tick.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/Tick 60x60.png"))); // NOI18N
        background.add(Tick, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 60, 60));

        pagoExitoso.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        pagoExitoso.setForeground(new java.awt.Color(0, 0, 0));
        pagoExitoso.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pagoExitoso.setText("Pago Exitoso");
        background.add(pagoExitoso, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 180, 50));

        mensajeTxt.setBackground(new java.awt.Color(0, 0, 0));
        mensajeTxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mensajeTxt.setForeground(new java.awt.Color(0, 0, 0));
        mensajeTxt.setText(" Se le enviara un correo electronico con el comprobante de pago.");
        background.add(mensajeTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 400, 30));

        okBtn.setBackground(new java.awt.Color(67, 159, 70));

        okBtnTxt.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        okBtnTxt.setForeground(new java.awt.Color(255, 255, 255));
        okBtnTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        okBtnTxt.setText("MENU");
        okBtnTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        okBtnTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                okBtnTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                okBtnTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                okBtnTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout okBtnLayout = new javax.swing.GroupLayout(okBtn);
        okBtn.setLayout(okBtnLayout);
        okBtnLayout.setHorizontalGroup(
            okBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(okBtnTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );
        okBtnLayout.setVerticalGroup(
            okBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(okBtnTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        background.add(okBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 120, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okBtnTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_okBtnTxtMouseClicked
        Menu menu = new Menu();
        menu.setVisible(true);
        menu.pack();
        menu.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_okBtnTxtMouseClicked

    private void okBtnTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_okBtnTxtMouseEntered
        okBtn.setBackground(new Color(67,185,70));
    }//GEN-LAST:event_okBtnTxtMouseEntered

    private void okBtnTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_okBtnTxtMouseExited
        okBtn.setBackground(new Color(67,159,70));
    }//GEN-LAST:event_okBtnTxtMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PagoExitoso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PagoExitoso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PagoExitoso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PagoExitoso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PagoExitoso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Tick;
    private javax.swing.JPanel background;
    private javax.swing.JLabel mensajeTxt;
    private javax.swing.JPanel okBtn;
    private javax.swing.JLabel okBtnTxt;
    private javax.swing.JLabel pagoExitoso;
    // End of variables declaration//GEN-END:variables
}
