/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Medico;
import Containers.ContenedoraSocio;
import Mail.Correos;
import Model.Socio;
import org.netbeans.lib.awtextra.AbsoluteConstraints;
import org.netbeans.lib.awtextra.AbsoluteLayout;

import java.awt.*;
import java.awt.event.ActionEvent;

import java.awt.event.MouseEvent;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;

import javax.imageio.ImageIO;
import javax.swing.*;
import javax.swing.border.BevelBorder;


/**
 *
 * @author sanch
 */
public class DetalleSocio extends JFrame {

    private String emailS;
    private String nameS;
    private Socio socioS=new Socio();
    /**
     * Creates new form DetalleSocio
     */
    
    public DetalleSocio(Socio socio) {
        initComponents();
        try{
            File iconFile = new File("src/com/images/LOGO1.png"); // Ruta de tu imagen
            BufferedImage iconImage = ImageIO.read(iconFile);
            setIconImage(iconImage);
        }catch (IOException ex) {
            ex.printStackTrace();
        }

        socioS=socio;
        MotivoTxtField.setVisible(false);
        jLabel1.setVisible(false);
        emailS=socio.getEmail();
        nameS=socio.getNombre();
        LegajoLabel.setText("Legajo nro: " + socio.getLegajo());
        NombreLabel.setText("Nombre: " + nameS);
        ApellidoLabel.setText("Apellido: " + socio.getApellido());
        String filePath = "src/com/imagesPersonas/" + socio.getLegajo() + ".png";
        File file = new File(filePath);
        if (file.exists()) {
            ImageIcon icon = new ImageIcon(new ImageIcon(filePath).getImage().getScaledInstance(fotoUsuario.getWidth(), fotoUsuario.getHeight(), Image.SCALE_SMOOTH));
            fotoUsuario.setIcon(icon);
        }
        // Continúa inicializando otros componentes y mostrando los otros datos del socio si es necesario
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        Marco = new javax.swing.JLabel();
        fotoUsuario = new javax.swing.JLabel();
        backMenuBtn = new javax.swing.JButton();
        MotivoTxtField = new javax.swing.JTextField();
        ApellidoLabel = new javax.swing.JLabel();
        NombreLabel = new javax.swing.JLabel();
        confirmBtn = new javax.swing.JButton();
        LegajoLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        miniBack = new javax.swing.JLabel();
        pelota6 = new javax.swing.JLabel();
        pelota5 = new javax.swing.JLabel();
        pelota4 = new javax.swing.JLabel();
        pelota3 = new javax.swing.JLabel();
        pelota2 = new javax.swing.JLabel();
        pelota1 = new javax.swing.JLabel();
        fondo_2 = new javax.swing.JLabel();
        fondo_1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Background.setBackground(new java.awt.Color(255, 255, 255));
        Background.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 255, 204), 2));
        Background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Marco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagesPersonas/marcoPerso.png"))); // NOI18N
        Background.add(Marco, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, -10, 250, 200));

        fotoUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/FotoCarnet.png"))); // NOI18N
        fotoUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
            }
        });
        Background.add(fotoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, 150, 140));

        backMenuBtn.setText("Volver al menu");
        backMenuBtn.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        backMenuBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMenuBtnMouseClicked(evt);
            }
        });
        backMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backMenuBtnActionPerformed(evt);
            }
        });
        Background.add(backMenuBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 330, 110, 50));

        MotivoTxtField.setColumns(5);
        MotivoTxtField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        MotivoTxtField.setToolTipText("");
        MotivoTxtField.setAutoscrolls(false);
        MotivoTxtField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        MotivoTxtField.setMinimumSize(new java.awt.Dimension(64, 26));
        MotivoTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MotivoTxtFieldActionPerformed(evt);
            }
        });
        Background.add(MotivoTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 360, 50));

        ApellidoLabel.setText("Apellido:");
        Background.add(ApellidoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 240, -1));
        this.setVisible(false);

        NombreLabel.setText("Nombre:");
        Background.add(NombreLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 210, -1));
        this.setVisible(false);

        confirmBtn.setText("Confirmar");
        confirmBtn.setToolTipText("");
        confirmBtn.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        confirmBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                try {
                    confirmBtnMouseClicked(evt);
                } catch (Exception e) {
                    throw new RuntimeException(e);
                }
            }
        });
        confirmBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmBtnActionPerformed(evt);
            }
        });
        Background.add(confirmBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, 105, 50));

        LegajoLabel.setText("Legajo nro:");
        Background.add(LegajoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 170, -1));
        this.setVisible(false);

        jLabel1.setText("Motivo del rechazo:");
        Background.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, -1, 30));
        this.setVisible(false);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aprobar", "Rechazar" }));
        jComboBox1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        Background.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, 125, -1));

        miniBack.setBackground(new java.awt.Color(245, 247, 245));
        miniBack.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 255, 204)));
        miniBack.setOpaque(true);
        Background.add(miniBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 420, 340));

        pelota6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/medicine.png"))); // NOI18N
        Background.add(pelota6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, -140, -1, -1));

        pelota5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/medicine.png"))); // NOI18N
        Background.add(pelota5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 230, 290, 270));

        pelota4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/medicine.png"))); // NOI18N
        Background.add(pelota4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-100, -10, -1, -1));

        pelota3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/medicine.png"))); // NOI18N
        Background.add(pelota3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 210, -1, -1));

        pelota2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/medicine.png"))); // NOI18N
        Background.add(pelota2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, -1, -1));

        pelota1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/medicine.png"))); // NOI18N
        Background.add(pelota1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, -70, -1, -1));

        fondo_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/Rectangle 1.png"))); // NOI18N
        Background.add(fondo_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, -20, 570, 370));

        fondo_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/Rectangle 1.png"))); // NOI18N
        Background.add(fondo_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, -20, 750, 510));

        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backMenuBtnActionPerformed(ActionEvent evt) {//GEN-FIRST:event_backMenuBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backMenuBtnActionPerformed

    private void backMenuBtnMouseClicked(MouseEvent evt) {//GEN-FIRST:event_backMenuBtnMouseClicked
 Medico medico = new Medico();
            medico.setVisible(true);
            medico.pack();
            medico.setLocationRelativeTo(null);
            this.dispose();
    }//GEN-LAST:event_backMenuBtnMouseClicked

    private void jComboBox1ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
                                          
    String selectedOption = (String) jComboBox1.getSelectedItem();
    if (selectedOption.equals("Rechazar")) {
        // Establecer la visibilidad del JTextField
        MotivoTxtField.setVisible(true);
        jLabel1.setVisible(true);
        // Ajustar el tamaño del JFrame y JPane
    } else {
        // Si no es "Rechazar", ocultar el JTextField
        MotivoTxtField.setVisible(false);
        jLabel1.setVisible(false);
        // Ajustar el tamaño del JFrame y JPanel
   
    }

    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void confirmBtnMouseClicked(MouseEvent evt) throws Exception {
        Correos mail = new Correos();
        ContenedoraSocio contenedoraSocio = new ContenedoraSocio(); // Inicialización de contenedoraSocio

        String selectedOption = (String) jComboBox1.getSelectedItem();

        try {
            contenedoraSocio.cargarSociosDeJson("Socios.json"); // Carga de socios desde JSON
        } catch (IOException e) {
            e.printStackTrace();
            // Manejo de errores durante la carga del JSON
        }

        Socio aptoSocio = contenedoraSocio.buscar(socioS.getLegajo()); // Buscar el socio correspondiente

        if (aptoSocio != null) {
            if (selectedOption.equals("Aprobar")) {
                aptoSocio.setAptoMedico(true);
                contenedoraSocio.modificacion(aptoSocio); // Modificar el socio en contenedoraSocio
                try {
                    contenedoraSocio.guardarSociosEnJson("Socios.json"); // Guardar cambios en el JSON
                } catch (IOException e) {
                    e.printStackTrace();
                    // Manejo de errores durante el guardado del JSON
                }

                // Iniciar hilo para enviar correo de apto médico exitoso
                new Thread(() -> {
                    try {
                        mail.CorreoAptoMedicoExitoso(emailS, nameS);
                    } catch (Exception e) {
                        e.printStackTrace();
                        // Manejo de errores durante el envío del correo
                    }
                }).start();
            } else {
                aptoSocio.setAptoMedico(false);
                contenedoraSocio.modificacion(aptoSocio);
                try {
                    contenedoraSocio.guardarSociosEnJson("Socios.json");
                } catch (IOException e) {
                    e.printStackTrace();
                }

                new Thread(() -> {
                    try {
                        mail.CorreoAptoMedicoRechazado(emailS, nameS, MotivoTxtField.getText());
                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                }).start();
            }
        } else {
            System.out.println("No se encontró el socio con legajo: " + socioS.getLegajo());
        }

        backMenuBtnMouseClicked(evt); // Volver al menú principal
    }                                       

    private void confirmBtnActionPerformed(ActionEvent evt) {//GEN-FIRST:event_confirmBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmBtnActionPerformed

    private void MotivoTxtFieldActionPerformed(ActionEvent evt) {//GEN-FIRST:event_MotivoTxtFieldActionPerformed
       
    }//GEN-LAST:event_MotivoTxtFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ApellidoLabel;
    private javax.swing.JPanel Background;
    private javax.swing.JLabel LegajoLabel;
    private javax.swing.JLabel Marco;
    private javax.swing.JTextField MotivoTxtField;
    private javax.swing.JLabel NombreLabel;
    private javax.swing.JButton backMenuBtn;
    private javax.swing.JButton confirmBtn;
    private javax.swing.JLabel fondo_1;
    private javax.swing.JLabel fondo_2;
    private javax.swing.JLabel fotoUsuario;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel miniBack;
    private javax.swing.JLabel pelota1;
    private javax.swing.JLabel pelota2;
    private javax.swing.JLabel pelota3;
    private javax.swing.JLabel pelota4;
    private javax.swing.JLabel pelota5;
    private javax.swing.JLabel pelota6;
    // End of variables declaration//GEN-END:variables
}
