/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Medico;
import Model.Categoria;
import Containers.ContenedoraSocio;
import Login.Login;
import Model.Socio;
import java.awt.Color;
import java.io.IOException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.HashMap;
import java.util.List;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author sanch
 */
public class Medico extends javax.swing.JFrame {

    int xMouse, yMouse;
    public Medico() {
        
        initComponents();
        setDate();
        actualizarTabla();
        volverMenuBtn.requestFocusInWindow();
        TablaSoc.getTableHeader().setReorderingAllowed(false);


    }
private void setDate(){
        LocalDate now = LocalDate.now();
        int year = now.getYear();
        int dia = now.getDayOfMonth();
        int month = now.getMonthValue();
        String[] meses = {"Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre"};
        dateText1.setText(dia+" de "+meses[month -1]+" de "+year);
    }  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        administracionTxt = new javax.swing.JLabel();
        dateText1 = new javax.swing.JLabel();
        dateText = new javax.swing.JLabel();
        dateText2 = new javax.swing.JLabel();
        exitMenu = new javax.swing.JPanel();
        exitBtn = new javax.swing.JPanel();
        exitTxt = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tituloSocios = new javax.swing.JLabel();
        buscarLabel = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaSoc = new javax.swing.JTable();
        buscarBtn = new javax.swing.JPanel();
        buscarTxt = new javax.swing.JLabel();
        volverMenuBtn = new javax.swing.JPanel();
        volverMenuTxt = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setName("MedicosBack"); // NOI18N
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(50, 115, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        administracionTxt.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        administracionTxt.setForeground(new java.awt.Color(255, 255, 255));
        administracionTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        administracionTxt.setText("Oficina medica");
        jPanel1.add(administracionTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, 32));

        dateText1.setFont(new java.awt.Font("Roboto", 1, 30)); // NOI18N
        dateText1.setForeground(new java.awt.Color(255, 255, 255));
        dateText1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dateText1.setText("{dayname} {day} de {month} de {year} ");
        jPanel1.add(dateText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        dateText.setFont(new java.awt.Font("Roboto", 1, 30)); // NOI18N
        dateText.setForeground(new java.awt.Color(255, 255, 255));
        dateText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dateText.setText("Medico Deportivo");
        jPanel1.add(dateText, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 100, -1, -1));

        dateText2.setFont(new java.awt.Font("Roboto", 1, 30)); // NOI18N
        dateText2.setForeground(new java.awt.Color(255, 255, 255));
        dateText2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dateText2.setText("Dr. Ivan Salvetti");
        jPanel1.add(dateText2, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 60, -1, -1));

        exitMenu.setBackground(new java.awt.Color(255, 255, 255));
        exitMenu.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                exitMenuMouseDragged(evt);
            }
        });
        exitMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                exitMenuMousePressed(evt);
            }
        });
        exitMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exitBtn.setBackground(new java.awt.Color(255, 255, 255));

        exitTxt.setBackground(new java.awt.Color(0, 0, 0));
        exitTxt.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        exitTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitTxt.setText("X");
        exitTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitTxtMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                exitTxtMousePressed(evt);
            }
        });

        javax.swing.GroupLayout exitBtnLayout = new javax.swing.GroupLayout(exitBtn);
        exitBtn.setLayout(exitBtnLayout);
        exitBtnLayout.setHorizontalGroup(
            exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
            .addGroup(exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(exitBtnLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(exitTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        exitBtnLayout.setVerticalGroup(
            exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
            .addGroup(exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(exitBtnLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(exitTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        exitMenu.add(exitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 0, -1, -1));

        jPanel1.add(exitMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/logoMedicina.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 40, 130, 120));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, -1));

        tituloSocios.setFont(new java.awt.Font("Corbel", 1, 28)); // NOI18N
        tituloSocios.setForeground(new java.awt.Color(153, 153, 153));
        tituloSocios.setText("Socios");
        getContentPane().add(tituloSocios, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 184, -1, -1));

        buscarLabel.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        buscarLabel.setForeground(new java.awt.Color(153, 153, 153));
        buscarLabel.setText(" Ingrese el legajo del socio a buscar.");
        buscarLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        buscarLabel.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                buscarLabelFocusLost(evt);
            }
        });
        buscarLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buscarLabelMousePressed(evt);
            }
        });
        buscarLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarLabelActionPerformed(evt);
            }
        });
        getContentPane().add(buscarLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 224, 780, 39));

        TablaSoc.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        TablaSoc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Legajo", "Nombre", "Apellido", "Email", "Documento", "Fecha de nacimiento", "Telefono", "Domicilio", "Sexo", "Obra Social", "Apto Medico", "Categoria"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TablaSoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                try {
                    TablaSocMouseClicked(evt);
                } catch (Exception e) {
                    throw new RuntimeException(e);
                }
            }
        });
        jScrollPane2.setViewportView(TablaSoc);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 285, 1270, 310));

        buscarBtn.setBackground(new java.awt.Color(50, 115, 153));
        buscarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buscarBtnMouseClicked(evt);
            }
        });

        buscarTxt.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        buscarTxt.setForeground(new java.awt.Color(255, 255, 255));
        buscarTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        buscarTxt.setLabelFor(buscarBtn);
        buscarTxt.setText("Buscar");
        buscarTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buscarTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buscarTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buscarTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buscarTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout buscarBtnLayout = new javax.swing.GroupLayout(buscarBtn);
        buscarBtn.setLayout(buscarBtnLayout);
        buscarBtnLayout.setHorizontalGroup(
            buscarBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
            .addGroup(buscarBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(buscarTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        buscarBtnLayout.setVerticalGroup(
            buscarBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
            .addGroup(buscarBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(buscarTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
        );

        getContentPane().add(buscarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(804, 224, -1, 40));

        volverMenuBtn.setBackground(new java.awt.Color(50, 115, 153));
        volverMenuBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                volverMenuBtnMouseClicked(evt);
            }
        });

        volverMenuTxt.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        volverMenuTxt.setForeground(new java.awt.Color(255, 255, 255));
        volverMenuTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        volverMenuTxt.setLabelFor(buscarBtn);
        volverMenuTxt.setText("Volver al Menu");
        volverMenuTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        volverMenuTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                volverMenuTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                volverMenuTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                volverMenuTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout volverMenuBtnLayout = new javax.swing.GroupLayout(volverMenuBtn);
        volverMenuBtn.setLayout(volverMenuBtnLayout);
        volverMenuBtnLayout.setHorizontalGroup(
            volverMenuBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
            .addGroup(volverMenuBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(volverMenuTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE))
        );
        volverMenuBtnLayout.setVerticalGroup(
            volverMenuBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
            .addGroup(volverMenuBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(volverMenuTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
        );

        getContentPane().add(volverMenuBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 640, 170, 50));

        getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buscarBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscarBtnMouseClicked
        try {
            ContenedoraSocio contenedoraSocio = new ContenedoraSocio();
            contenedoraSocio.cargarSociosDeJson("Socios.json");
            DefaultTableModel model = (DefaultTableModel) TablaSoc.getModel();
            model.setRowCount(0);
            String legajoStr = buscarLabel.getText().trim();

            if (legajoStr.isEmpty() || legajoStr.equals("Ingrese el legajo del socio a buscar.")) {
                contenedoraSocio.listar().values().forEach(this::addSocioToTable);
            } else {
                int legajo = Integer.parseInt(legajoStr);
                Socio socio = contenedoraSocio.buscar(legajo);
                addSocioToTable(socio);
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_buscarBtnMouseClicked

    private void buscarTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscarTxtMouseExited
        buscarBtn.setBackground(new Color(59,132,173));
    }//GEN-LAST:event_buscarTxtMouseExited

    private void buscarTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscarTxtMouseEntered
        buscarBtn.setBackground(new Color(80,139,166));
    }//GEN-LAST:event_buscarTxtMouseEntered

    private void buscarTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscarTxtMouseClicked
        this.buscarBtnMouseClicked(evt);
    }//GEN-LAST:event_buscarTxtMouseClicked

    private void TablaSocMouseClicked(java.awt.event.MouseEvent evt) throws Exception {//GEN-FIRST:event_TablaSocMouseClicked
        if(evt.getClickCount()==2){
            int filaSeleccionada = TablaSoc.getSelectedRow();
            if (filaSeleccionada != -1) {

                int legajo = (int) TablaSoc.getValueAt(filaSeleccionada, 0);
                Socio socio = new Socio();
                ContenedoraSocio contenedoraSocio = new ContenedoraSocio();
                contenedoraSocio.cargarSociosDeJson("Socios.json");
                socio = contenedoraSocio.buscar(legajo);

                DetalleSocio detalleSocio = new DetalleSocio(socio);
                detalleSocio.setVisible(true);
                detalleSocio.pack();
                detalleSocio.setLocationRelativeTo(null);
                this.dispose();
            }
        }
    }//GEN-LAST:event_TablaSocMouseClicked

    private void buscarLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarLabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscarLabelActionPerformed

    private void buscarLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscarLabelMousePressed
        if(buscarLabel.getText().equals(" Ingrese el legajo del socio a buscar.")){
            buscarLabel.setText("");
            buscarLabel.setForeground(Color.black);
        }
    }//GEN-LAST:event_buscarLabelMousePressed

    private void buscarLabelFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_buscarLabelFocusLost
        if (buscarLabel.getText().isEmpty()) {
            buscarLabel.setText(" Ingrese el legajo del socio a buscar.");
            buscarLabel.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_buscarLabelFocusLost

    private void exitMenuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMenuMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_exitMenuMousePressed

    private void exitMenuMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMenuMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_exitMenuMouseDragged

    private void exitTxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_exitTxtMousePressed

    private void exitTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMouseExited
        exitBtn.setBackground(Color.white);
        exitTxt.setForeground(Color.black);
    }//GEN-LAST:event_exitTxtMouseExited

    private void exitTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMouseEntered
        exitBtn.setBackground(Color.red);
        exitTxt.setForeground(Color.white);
    }//GEN-LAST:event_exitTxtMouseEntered

    private void exitTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitTxtMouseClicked

    private void volverMenuTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volverMenuTxtMouseClicked
        Login login = new Login();
        login.setVisible(true);
        login.pack();
        login.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_volverMenuTxtMouseClicked

    private void volverMenuTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volverMenuTxtMouseEntered
        volverMenuBtn.setBackground(new Color(80,139,166));
    }//GEN-LAST:event_volverMenuTxtMouseEntered

    private void volverMenuTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volverMenuTxtMouseExited
        volverMenuBtn.setBackground(new Color(59,132,173));
    }//GEN-LAST:event_volverMenuTxtMouseExited

    private void volverMenuBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volverMenuBtnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_volverMenuBtnMouseClicked



    private void addSocioToTable(Socio socio) {
        DefaultTableModel model = (DefaultTableModel) TablaSoc.getModel();
        model.addRow(new Object[]{socio.getLegajo(), socio.getNombre(), socio.getApellido(), socio.getEmail(), socio.getDni(), socio.getFechaDeNacimiento(), socio.getTelefono(), socio.getDomicilio(), socio.getSexo(), socio.getObraSocial(), socio.isAptoMedico(), socio.getCategoria(), socio.getFechaVencimientoPago()});
    }

    public Object[] socioToRow(Socio socio) {
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        return new Object[] {
                socio.getLegajo(),
                socio.getNombre(),
                socio.getApellido(),
                socio.getEmail(),
                socio.getDni(),
                socio.getFechaDeNacimiento(),
                socio.getTelefono(),
                socio.getDomicilio(),
                socio.getSexo(),
                socio.getObraSocial(),
                socio.isAptoMedico(),
                socio.getCategoria(),
                socio.getFechaVencimientoPago().format(formatter)
        };
    }

    public HashMap<Integer, Socio> obtenerListaDeSocios() {
        ContenedoraSocio contenedoraSocio = new ContenedoraSocio();
        try {
            contenedoraSocio.cargarSociosDeJson("Socios.json");
        } catch (IOException e) {
            e.printStackTrace();
        }
        return contenedoraSocio.listar();
    }



    public void llenarTablaConSocios(HashMap<Integer, Socio> listaDeSocios) {
        DefaultTableModel model = (DefaultTableModel) TablaSoc.getModel();
        model.setRowCount(0); // Limpia la tabla existente

        // Convertir los valores del mapa a una lista para ordenar por legajo
        List<Socio> sociosOrdenados = new ArrayList<>(listaDeSocios.values());
        sociosOrdenados.sort(Comparator.comparingInt(Socio::getLegajo)); // Ordenar por legajo ascendente

        // Agregar los socios ordenados a la tabla
        for (Socio socio : sociosOrdenados) {
            model.addRow(socioToRow(socio));
        }
    }

    // Llamada al método para llenar la tabla
    public void actualizarTabla() {
        HashMap<Integer, Socio> socios = obtenerListaDeSocios(); // Método que devuelve la lista de socios
        llenarTablaConSocios(socios);
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaSoc;
    private javax.swing.JLabel administracionTxt;
    private javax.swing.JPanel buscarBtn;
    private javax.swing.JTextField buscarLabel;
    private javax.swing.JLabel buscarTxt;
    private javax.swing.JLabel dateText;
    private javax.swing.JLabel dateText1;
    private javax.swing.JLabel dateText2;
    private javax.swing.JPanel exitBtn;
    private javax.swing.JPanel exitMenu;
    private javax.swing.JLabel exitTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel tituloSocios;
    private javax.swing.JPanel volverMenuBtn;
    private javax.swing.JLabel volverMenuTxt;
    // End of variables declaration//GEN-END:variables
}
